spring:
  application:
    name: eureka-service
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
        defaultZone: http://127.0.0.1:8002/eureka/

server:
  port: 8002


